version: '3.8'

services:
  pocketbase:
    image: cotontigeh/pocketbase:latest
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_migrations:/pb/pb_migrations
    ports:
      - "8080:8080"
